#!/bin/bash

source /etc/profile

# POST-RECEIVE HOOK
# ARGV: empty
# STDIN: [OLD HEAD] [NEW HEAD] refs/heads/alpha
set -- $(cat /dev/stdin)

old=$1 && new=$2 && ref=$3
branch=$(basename $ref)

# POST-UPDATE HOOK
# ARGV: $1 is branch
# STDIN: ?
#branch=$(basename $1)

cd ..
root=`pwd`

# GIT_DIR is "." which should points to bare repozitory
GIT_DIR="`pwd`/$branch/.git"

# colors
red()   { echo -e "\e[1;31m$*\e[0m"; }
green() { echo -e "\e[1;32m$*\e[0m"; }
blue()  { echo -e "\e[1;34m$*\e[0m"; }

if [ -d "$branch" ] ; then
  cd $branch
  blue "Updating $branch in `pwd` ... (from $old' to '$new')"
  git reset --hard
  git pull
else
  blue "Cloning $branch to $(pwd)/$branch (HEAD: '$new') ..."
  git clone repo.git $branch
  cd $branch
  git checkout $branch
  blue "Creating logs ..."
  mkdir log tmp 2> /dev/null
  touch log/apache.log tmp/restart.txt
  # global hooks
  # /webs/static/hooks/update
  if [ -x "$root/../support/hooks/clone" ] ; then
    blue "Runnings global clone hook"
    $root/../support/hooks/clone
  fi
fi

# vhosts
vhost="$root/vhosts/$branch.vhost"
vhostgen="$root/../support/tools/vhost-gen"
if ! [ -f "$vhost" ] ; then
  green "Creating vhost file in $vhost ..."
  mkdir $(dirname $vhost) 2> /dev/null
  if [ -x "$vhostgen" ] ; then
    $vhostgen $root $branch > $vhost
  else
    vhost-gen.rb $root $branch > $vhost
  fi
  #httpd -k restart
  # TODO: how to restart apache as user?
  green "Restart Apache please"
  echo
  green "You should setup data sources. Possibilities are:"
  green "  - symlink production database: just if db structure is same"
  green "  - copy production database: just if db structure is same"
  green "  - use fixtures: in another cases"
fi

# HOOKS
# Run first found hook

# local hooks
if [ -x "support/hooks/update" ] ; then
  blue "Runnings project's update hook"
  exec support/hooks/update
fi

# global hooks
# /webs/static/hooks/update
if [ -x "../../support/hooks/update" ] ; then
  blue "Runnings global update hook"
  exec ../../support/hooks/update
fi
