#!/bin/bash

# POST-RECEIVE HOOK
# ARGV: empty
# STDIN: [OLD HEAD] [NEW HEAD] refs/heads/alpha

# go to the project directory
cd ..

# extend $PATH
source /etc/profile

# STDIN will be ARGV
set -- $(cat /dev/stdin)

# replace this wrapper with ruby script
branch=$(basename $3)
exec GIT_DIR="$PWD/$branch/.git" /webs/support/git-deploy/post-receive.rb $branch
