#!/usr/bin/env ruby

require "find"
require "git-deployer/common"

Dir.chdir("web") do
  if File.exist?("production.db")
    note "Note: maybe db will need to be deleted and recreated, if you have changed some model's structure."
  else
    info "Running syncdb ..."
    rm "development.db"
    python "manage.py syncdb --noinput"
    if File.exist?("fixtures.json")
      info "Loading fixtures ..."
      python "manage.py loaddata fixtures.json"
    end
  end
  restart_application
end