#!/usr/bin/env ruby

require "git-deployer/common"

# tmp for tmp/restart.txt
mkdir "tmp"

@branch = File.basename(Dir.pwd)
@path = Dir.pwd
@project = File.dirname(Dir.pwd)
ruby = "ruby"

# dytrych vs. botablog.cz
@env = @project.match(/\./) && @branch.eql?("master") ? "production" : "development"

puts "config/settings_local.rb ...".blue.bold
File.open("config/database.yml", "w") do |file|
  if @env == "production"
  file.puts <<EOF
---
production: &defaults
  adapter:  sqlite3
  database: production.db
EOF
  elsif @env == "development"
  file.puts <<EOF
---
development: &defaults
  adapter:  sqlite3
  database: development.db
EOF
  end
end

if @env == "production"
  puts "Symlinking database into #{ENV['BACKUPDIR']}/database/#{File.basename(@project)}.db ...".blue.bold
  system("ln -s #{Dir.pwd}/production.db #{ENV['BACKUPDIR']}/database/#{File.basename(@project)}.db")
  if File.directory?("media/uploads")
    puts "Symlinking uploads into #{ENV['BACKUPDIR']}/uploads/#{File.basename(@project)} ...".blue.bold
    system("ln -s #{Dir.pwd}/media/uploads/ #{ENV['BACKUPDIR']}/uploads/#{File.basename(@project)}")
  end
end
